[package]
org = "ballerina"
name = "sql"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "time"
version = "@stdlib.time.version@"

[[dependency]]
org = "ballerina"
name = "config"
version = "@stdlib.config.version@"

[[platform.java11.dependency]]
path = "../sql-native/build/libs/sql-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "sql-native"
version = "@project.version@"

[[platform.java11.dependency]]
path = "./lib/HikariCP-3.3.1.jar"
groupId = "com.zaxxer"
artifactId = "HikariCP"
version = "3.3.1"

[[platform.java11.dependency]]
path = "./lib/hsqldb-2.5.1.jar"
groupId = "org.hsqldb"
scope = "testOnly"
artifactId = "hsqldb"
version = "2.5.1"
