[package]
org = "ballerina"
name = "sql"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS"]
repository = "https://github.com/ballerina-platform/module-ballerina-sql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "@toml.version@"
path = "../native/build/libs/sql-native-@project.version@.jar"

[[platform.java21.dependency]]
path = "../test-utils/build/libs/sql-test-utils-@project.version@.jar"
scope = "testOnly"

[[platform.java21.dependency]]
groupId = "com.zaxxer"
artifactId = "HikariCP"
version = "@hikaricp.lib.version@"
path = "./lib/HikariCP-@hikaricp.lib.version@.jar"

[[platform.java21.dependency]]
path = "./lib/hsqldb-@hsql.connector.version@.jar"
scope = "testOnly"
